### ISSUE TITLE
Consider adding a CHANGES.md or similar

### ISSUE THREAD

**Issue by christianromney** [propan/geheimtur#12]
1. Love this project. :)
2. It would be super helpful to understand what changes (especially *breaking* changes) were introduced  from version to version without needing to view the Git log / read all of the code to find out. 

For instance, I am still running version 0.2.1 and would like to be on the latest stable release, but have to do some log surfing to figure out if/how the changes might affect my application. Again, thank you for releasing this project. Cheers!

**Comment by propan** [comment]
Hi Christian!

I hope I haven't caused too much problems with the breaking changes.
I've been thinking about that issue myself, but I could not come up with a good way to report them.

Have you seen any good examples somewhere in the wild? I can describe at least the changes from 0.2.1 to 0.3.0.

Pavel

**Comment by christianromney** [comment]
Hi Pavel,

I haven't upgraded from 0.2.1—0.3.0 because I wasn't sure what the breaking changes were. I *plan* to upgrade but was putting it off until I either had a chance to review the changes myself by going through the diff or by asking you if you would be kind enough to list them out.  :)

Again, thanks for open sourcing this project. I have found it very useful and point everyone using Pedestal to it.

**Comment by propan** [comment]
Hi Christian,

sorry for the delay. Hope you find the migration instructions helpful.
