### ISSUE TITLE
Extra query params per provider?

### ISSUE THREAD

**Issue by milt** [propan/geheimtur#17]
First off, thanks for your great work on this!

We've run into a problem while implementing a Google provider, namely that Geheimtur doesn't allow the addition of extra query params to initial auth requests in `geheimtur.impl.oauth2/authenticate-handler`.  This is a bit of a dealbreaker with providers like Google that (annoyingly) use extra params to control requested access. For instance, the `access_type` param controls [whether or not a refresh token will be available](https://developers.google.com/identity/protocols/OAuth2WebServer) (see "Step 2").

This could be alleviated pretty easily by adding a key to the provider map with a map value which would be converted to additional query params.

**Comment by propan** [comment]
Resolved by #19

**Comment by propan** [comment]
Thank you! This is available in 0.3.3.
