### ISSUE TITLE
Client secret rotation

### ISSUE THREAD

**Issue by Otann** [propan/geheimtur#21]
Hi!

While using geheimtur, I encountered a problem, where my app cannot login new users after a day of uptime. I've discovered that in our company keys are rotated daily, and my app was using outdated one.

I see in the code of `geheimtur.impl.oauth2/authenticate-handler` handler is created and is bound to the value it reads from `providers` map.

Could you please consider adding an option to give providers-fn that will provide value in runtime or some similar functionality?

And of course, thank you for the excellent library.

**Comment by Otann** [comment]
I think it's rather `geheimtur.impl.oauth2/callback-handler` where client-secret is used

**Comment by propan** [comment]
Hi!

I created a new branch [oauth-providers-map-or-fn](https://github.com/propan/geheimtur/commit/777bced93fc93606e9f4b274801e8c01da725249) that should allow to pass a function that returns OAuth providers configuration. You can see how it is used in the updated tests.

Would something like that work for you?

**Comment by Otann** [comment]
Sorry for a very not responding back, my project where I intended to use it was frozen.
Yes, this would work perfectly.

I am very grateful that you addressed this nevertheless!
