### ISSUE TITLE
credentials extra arity with request

### ISSUE THREAD

**Issue by nickik** [propan/geheimtur#3]
I was thinking that sometimes it would be usful to have access to the request information when writing a credentials function. 

For example I was playing around with the idea of attaching a datomic db instance into the request. Then I would want to do the user lookup based on that db instance.

**Comment by anthgur** [comment]
:+1: this would be really useful. Is there a security reason to not do this or some way of using interceptors that would be more idiomatic?

**Comment by anthgur** [comment]
One possibility would be to have the oauth success callbacks and credential-fns be interceptors instead of thunks. We could have the respective workflows add the success interceptors into the path, and that way we can pass the full context through the success interceptors.

**Comment by propan** [comment]
There was no particular security reason behind that decision. I just wanted to keep the API as simple as possible without many knobs to tune before one can start using it.

The reason why I have been silent here (and I'm not happy about it), is that I'm still not quite sure that it's a good idea to pass the full context to a credential/callback function.

Could you explain your use case? Maybe we can come up with something.

**Comment by anthgur** [comment]
Thanks for replying!

I have a minimal description of one use case on [this commit's summary](https://github.com/anthgur/geheimtur/commit/245178c45ebb7bc1ba05e7d56e5dcb388a30f02e). The motivation is that applications need to associate the internal identities of users with those from external oauth providers. The idiomatic way to handle resources like database connections in pedestal is to have interceptors assoc them into the context. Changing the success handler api to take the full context offers application writers the flexibility required to perform those associations without forcing the callbacks to be closures over the required resources.

**Comment by anthgur** [comment]
Also I think I hijacked the topic of this particular issue; I don't think it was originally in reference to oauth.

**Comment by propan** [comment]
It makes sense to handle both cases the same (or similar) way, so that there are no inconsistencies in the API.

Let me think about it sometime.

**Comment by propan** [comment]
Starting with version 0.3.0 credential functions and the OAuth2 on-success callback function have the following signatures:

```clojure
(defn credential-fn
  [context {:keys [username password]}]
  ...)
```

```clojure
(defn on-success
  [context identity]
  ...)
```
