### ISSUE TITLE
basic auth wrong return code

### ISSUE THREAD

**Issue by langalex** [propan/geheimtur#4]
when a user accesses a resource restricted via basic auth, the return code should be 401 and not 403, so that the browser asks for the credentials again.

**Comment by propan** [comment]
Hi,

could you please expand on the problem that you have?

Currently, the interceptor sends 401 when there is no Authorization header present in the request. But if there is such a header and the credentials validation fails, it returns 403. (see https://github.com/propan/geheimtur/blob/master/src/geheimtur/impl/http_basic.clj )

Pavel

**Comment by langalex** [comment]
yes. what I'm asking to change is to keep sending a 401 if the credential validation fails.

what happens now:
* user goes to restricted resource, accidentally enters wrong password
* browser shows error messages but doesn't ask for correct password again

what should happen:
* after entering wrong password servers responds again with 401 and browser shows password dialog again

also see the [definition of 401](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html): The request requires user authentication. ***If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials.*** If the 401 response contains the same challenge as the prior response, and the user agent has already attempted authentication at least once, then the user SHOULD be presented the entity that was given in the response, since that entity might include relevant diagnostic information.

versus 403: The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated.

I would send a pull request but I'm a complete Clojure newbie and don't really know how.

**Comment by propan** [comment]
Sounds reasonable. I'll try to fix it during the weekend.

**Comment by propan** [comment]
I updated the demo to illustrate new behaviour: http://geheimtur.herokuapp.com/http-basic

**Comment by langalex** [comment]
thanks for the prompt implementation. works like a charm.
