### ISSUE TITLE
'fetch-token' assumes that the response is  form-urlencoded but that's not necessarily the case

### ISSUE THREAD

**Issue by ddeaguiar** [propan/geheimtur#7]
In the [fetch-token function](https://github.com/propan/geheimtur/blob/master/src/geheimtur/impl/oauth2.clj#L74), ring-codec/form-decode is used to parse the response. While this works with Github, I had issues setting up integration with [Google](https://developers.google.com/identity/protocols/OAuth2WebServer#handlingtheresponse) whose token response payload is json.

There are two ways that this can be handled:
1. Use different token response parse fn's based on the token response Content-Type
2. Allow the user to provide a token-response-parse-fn in the provider config

I'd prefer the former over the later. Pedestal already includes Cheshire so we can use it to parse json responses.

What are your thoughts? I'd be happy to work on a pull request.

**Comment by propan** [comment]
I would probably go with a combination of both: a decent default function that acts based on the response Content-Type so that it requires minimum configuration, but still allowing the user to redefine it .

Let me play around with the idea

**Comment by ddeaguiar** [comment]
Ok, thanks!

**Comment by propan** [comment]
I updated the demo application and now it includes logins via GitHub and Google.

Briefly, the solution I came up with is the following:

By default, the library uses `clj-http` response coercion feature to parse responses of the token and user details endpoints. It means that most of the time it should work out of the box.

Unfortunately, `clj-http` does not support coercion of `x-www-form-urlencoded` content type. I created a pull request https://github.com/dakrone/clj-http/pull/264 which hopefully will be merged and fix that.

Alternatively, you can change the behaviour by defining custom :token-parse-fn and :user-info-parse-fn parser functions in the provider configuration. You can find an example in the demo application where I use it to parse GitHub token response that comes as a `x-www-form-urlencoded` string.

I also changed the behaviour of :user-info-parse-fn to match :token-parse-fn.

**Comment by ddeaguiar** [comment]
I think this is a solid solution. Thanks for taking the time to look into it. I'll leave it to you to close the issue just in case you want to keep it open until dakrone/clj-http#264 is closed.
